# Rendering
backend = "glx";
vsync = true;

# Shadows (Makes Window Maker dockapps and menus look great)
shadow = true;
shadow-radius = 7;
shadow-offset-x = -7;
shadow-offset-y = -7;
shadow-exclude = [
  "class_g = 'Wmaker'",
  "name = 'Notification'",
  "window_type = 'dock'"
];

# Fading
fading = true;
fade-in-step = 0.03;
fade-out-step = 0.03;

